apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-staging
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./monitoring/controllers/staging"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: monitoring
  dependsOn:
    - name: monitoring-base
