apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-configmap
data:
  VIRTUAL_HOST: "pihole.morielclouds.com"
  WEBPASSWORD: "admin"  # Consider using a secret for passwords
  ServerIP: "10.43.94.9"