apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-configmap
data:
  TZ: "Europe/Berlin"
  DNSMASQ_LISTENING: "all"
  PIHOLE_DNS_: "1.1.1.1;8.8.8.8"
  VIRTUAL_HOST: "pihole.morielclouds.com"
  WEBPASSWORD: "admin"
  ServerIP: "10.43.94.9"