apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole

  template:
    metadata:
      labels:
        app: pihole


    spec:
      # securityContext:
      #   fsGroup: <user-id>
      #   runAsUser: <user-id>
      #   runAsGroup: <user-id>

      containers:
        - name: pihole

          image: pihole/pihole:latest

          envFrom:
            - configMapRef:
                name: pihole-configmap

          ports:
              - containerPort: 53
                protocol: TCP
              - containerPort: 53
                protocol: UDP
              - containerPort: 80
                protocol: TCP
              - containerPort: 443
                protocol: TCP

          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-storage

      restartPolicy: Always

      volumes:
        - name: pihole-storage
          persistentVolumeClaim:
            claimName: pihole-storage