apiVersion: v1
kind: Service
metadata:
  name: pihole-service
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: http
      port: 5080         # External port
      targetPort: 80     # Internal container port
      protocol: TCP
    - name: https
      port: 5443         # External port
      targetPort: 443
      protocol: TCP
