apiVersion: v1
kind: Service
metadata:
  name: pihole-service
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: http
      port: 8053        # Changed from 80
      targetPort: 80    # Pi-hole container still uses 80 internally
      protocol: TCP
    - name: https
      port: 8443       # Changed from 443
      targetPort: 443  # Pi-hole container still uses 443 internally
      protocol: TCP
