apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:glaWkp7YfxT3POcWlu4QLfz6ul+YbjRLgEi+qFUBsum37tS1HF1zzXn5CAYf/2vVOQa//S/0vAg=,iv:e4t2Ai7/uwAcArHN8Zef3c1DukjpB8aww2Pg9PRgkEs=,tag:FpM4nMDyC59N1Vsadkfi5g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    age:
        - recipient: age13wyxcsfwxsmn4gxj8vd8038t8lz9ley0f5y0pd0rvmzevjd3wfmsvqjgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQW8zK1c2K1hJay9ETlZp
            bVBuWWZvMC93b3FmbWdEZFE1dUdHVGJJVDFJCm1EUlkzYUdOdjRMcGZLVXJxUXh4
            eHoyODhsWlJpZU9IL0FlZmJOempuY2MKLS0tIG44TEFKQnNhc2NIWGV4U0k1WlhY
            eFNpUHdWNDFROER0L1ZnWTFXZlFVcU0KNi7902Q4DeeKYhqso7H8X9RwXNHKHcZ6
            WssjVbjFZ78hJK05gsZJ5xOVaobvi+G6h0JBtcjK0NWUkqW5Lq3IwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T19:58:23Z"
    mac: ENC[AES256_GCM,data:y6pzk1KJYvw6I60W2uL8gzRoPH7dOJxHhiFfgFAcdoCPmAP1mrp7xRBL4A4c+UHmN+e32EpubpRJy7XylPJyazzzeIdeUdQ9UMBAehm5JqIcfDl1Wp7mm23cJPzP/jvbLDl5C9AmF5C4/XO5rifTq7h4VxhmsmZ6qvOSvrlkHPc=,iv:N0fScYthnd1qFsm+9qYxtiQh8QHlkqHthPZo8c3NE7o=,tag:iPwaDJOtxMUH8cPADBaNwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
